### ISSUE TITLE
Epic: v0.1 (MVP)

### ISSUE THREAD

**Issue by ashes999** [ashes999/faithful-heart#1]
This is the simplest, smallest, fully-functional game. All the art looks like coloured rectangles. But, we solved all major technical and content risks.
# Risks/Spikes to Address
- Proper story and universe
  - [x] Plan out the story and backstory (high-level)
  - [x] Plan out lessons to learn, and ayaat to showcase
  - [ ] Plan out details of in-game events
  - [ ] Revisit ayaat/lessons and make sure it ties in well
- OUYA support
  - [x] Controller support
    - [x] Directional control
    - [x] Dead zones
  - [x] Resolution: 960x540 and scale up for OUYA
    - [x] Use RPG Maker art on 960x540 and see how it looks on OUYA (looks great)
    - [x] Use non-pixel art on 960x540 and see how it looks on OUYA (looks great)
  - Menus, etc. are navigatable by controller too
  - All UI elements are in the middle-ish of the screen (10-15% overdraw)
- Technical Unknowns
  - [ ] [Pixel perfect collisions for the weapon](https://github.com/HaxeFlixel/flixel-demos/blob/master/Performance/PixelPerfectCollision/source/PlayState.hx#L238)
- Art / Animation
  - [x] How many frames for each animation (eg. walking)? (~8)
  - [ ] Top-down, 3/4, or what perspective?
  - [ ] How many animations to attack? -- Two~~, four, or eight directions?~~
- Data-driven architecture
  - [ ] The game can be created from hard-coded data (no random).
  - [ ] All data exists in hand-editable text files (as JSON)
  - [ ] Randomize stuff (pure random, no rules)
  - [ ] Constrained random
# Prototypes to Try
- [ ] Basic shell: one room, grey-boxed, infinite action RPG battle; fighting, points, death.
- [ ] Test: as faith goes up, new, stronger monsters appear (percentage + threshold checks)
- [ ] Test: as faith goes down, your stats are temporarily dropped too.
# Deferred Features

Do these in the sequel.
- Plugins
  - Pick one major and one minor one to do (eg. Ancient Dungeon, a total conversion)
  - Technical assessment: Users have to make Neko builds or just data changes?
  - Make them work on OUYA somehow.
